version: "3.9"
services:
  life-counter-pg:
    image: "postgres:14"
    volumes:
      - D:\db\pg\life-counter:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
  life-counter-redis:
    image: "redis"
    command: redis-server --notify-keyspace-events "zxK"
    ports:
      - 6379:6379
  life-counter-gateway:
    image: "nginx"
    volumes:
      - "${USERPROFILE}\\AppData\\Roaming\\LifeCounter:/var/lifecounter"
      - ./local-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443